[project]
name = "docint"
version = "0.1.0"
description = "Proof of concept RAG application"
authors = [
  { name = "nos-tromo" }
]
requires-python = ">=3.11,<3.13"
license = "Apache-2.0"
dependencies = [
  "docling>=2.64.1",
  "fastapi>=0.116.1",
  "fastembed>=0.7.3",
  "fastparquet>=2024.11.0",
  "huggingface-hub>=0.36.0",
  "llama-index>=0.13.0",
  "llama-index-embeddings-huggingface>=0.6.0",
  "llama-index-llms-ollama>=0.7.0",
  "llama-index-node-parser-docling>=0.4.0",
  "llama-index-readers-docling>=0.4.0",
  "llama-index-vector-stores-qdrant>=0.7.1",
  "loguru>=0.7.2",
  "numpy>=1.26,<2.1",
  "numba>=0.61.0",
  "llvmlite>=0.44.0",
  "openai-whisper>=20250625",
  "opencv-python-headless>=4.11.0.86",
  "pandas>=2.2.3",
  "pillow>=11.3.0",
  "pyarrow>=21.0.0",
  "pydantic>=2.11.7",
  "pypdf>=6.4.1",
  "python-dotenv>=1.1.1",
  "python-magic>=0.4.27",
  "python-multipart>=0.0.20",
  "qdrant-client>=1.15.1",
  "requests>=2.32.5",
  "sqlalchemy>=2.0.42",
  "streamlit>=1.52.1",
  "torch>=2.7.1",
  "torchvision>=0.23.0",
  "uvicorn>=0.35.0",
  "watchdog>=6.0.0",
]

[project.scripts]
docint = "docint.app:run"
ingest = "docint.cli.ingest:main"
query = "docint.cli.query:main"
load-models = "docint.utils.model_cfg:main"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff==0.14.3",
]

[build-system]
requires = ["setuptools>=75.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["docint"]

[tool.uv]
package = true

[tool.uv.sources]
docint = { workspace = true }
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { index = "pytorch-cpu",  marker = "sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { index = "pytorch-cpu",  marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
